package com.comerzzia.iskaypet.pos.persistence.fidelizacion.fidelizados;

import java.util.Date;

public class LocalFidelizados extends LocalFidelizadosKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.NOMBRE
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.APELLIDOS
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String apellidos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.DOMICILIO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String domicilio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.LOCALIDAD
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String localidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.PROVINCIA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String provincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.CP
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String cp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.CODPAIS
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String codpais;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.CODTIPOIDEN
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String codtipoiden;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.DOCUMENTO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String documento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.FECHA_ALTA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private Date fechaAlta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.FECHA_MODIFICACION
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private Date fechaModificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.CODFIDELIZADO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String codfidelizado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.CODLENGUA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String codlengua;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.TELEFONO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.EMAIL
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.NUMERO_TARJETA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String numeroTarjeta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.FECHA_VERSION
	 * @mbggenerated  Thu Jan 16 17:04:58 CET 2025
	 */
	private Date fechaVersion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.NOMBRE
	 * @return  the value of x_local_fidelizados_tbl.NOMBRE
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.NOMBRE
	 * @param nombre  the value for x_local_fidelizados_tbl.NOMBRE
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre == null ? null : nombre.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.APELLIDOS
	 * @return  the value of x_local_fidelizados_tbl.APELLIDOS
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getApellidos() {
		return apellidos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.APELLIDOS
	 * @param apellidos  the value for x_local_fidelizados_tbl.APELLIDOS
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setApellidos(String apellidos) {
		this.apellidos = apellidos == null ? null : apellidos.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.DOMICILIO
	 * @return  the value of x_local_fidelizados_tbl.DOMICILIO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getDomicilio() {
		return domicilio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.DOMICILIO
	 * @param domicilio  the value for x_local_fidelizados_tbl.DOMICILIO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio == null ? null : domicilio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.LOCALIDAD
	 * @return  the value of x_local_fidelizados_tbl.LOCALIDAD
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getLocalidad() {
		return localidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.LOCALIDAD
	 * @param localidad  the value for x_local_fidelizados_tbl.LOCALIDAD
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setLocalidad(String localidad) {
		this.localidad = localidad == null ? null : localidad.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.PROVINCIA
	 * @return  the value of x_local_fidelizados_tbl.PROVINCIA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getProvincia() {
		return provincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.PROVINCIA
	 * @param provincia  the value for x_local_fidelizados_tbl.PROVINCIA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setProvincia(String provincia) {
		this.provincia = provincia == null ? null : provincia.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.CP
	 * @return  the value of x_local_fidelizados_tbl.CP
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getCp() {
		return cp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.CP
	 * @param cp  the value for x_local_fidelizados_tbl.CP
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setCp(String cp) {
		this.cp = cp == null ? null : cp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.CODPAIS
	 * @return  the value of x_local_fidelizados_tbl.CODPAIS
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getCodpais() {
		return codpais;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.CODPAIS
	 * @param codpais  the value for x_local_fidelizados_tbl.CODPAIS
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setCodpais(String codpais) {
		this.codpais = codpais == null ? null : codpais.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.CODTIPOIDEN
	 * @return  the value of x_local_fidelizados_tbl.CODTIPOIDEN
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getCodtipoiden() {
		return codtipoiden;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.CODTIPOIDEN
	 * @param codtipoiden  the value for x_local_fidelizados_tbl.CODTIPOIDEN
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setCodtipoiden(String codtipoiden) {
		this.codtipoiden = codtipoiden == null ? null : codtipoiden.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.DOCUMENTO
	 * @return  the value of x_local_fidelizados_tbl.DOCUMENTO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getDocumento() {
		return documento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.DOCUMENTO
	 * @param documento  the value for x_local_fidelizados_tbl.DOCUMENTO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setDocumento(String documento) {
		this.documento = documento == null ? null : documento.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.FECHA_ALTA
	 * @return  the value of x_local_fidelizados_tbl.FECHA_ALTA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public Date getFechaAlta() {
		return fechaAlta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.FECHA_ALTA
	 * @param fechaAlta  the value for x_local_fidelizados_tbl.FECHA_ALTA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.FECHA_MODIFICACION
	 * @return  the value of x_local_fidelizados_tbl.FECHA_MODIFICACION
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.FECHA_MODIFICACION
	 * @param fechaModificacion  the value for x_local_fidelizados_tbl.FECHA_MODIFICACION
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.CODFIDELIZADO
	 * @return  the value of x_local_fidelizados_tbl.CODFIDELIZADO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getCodfidelizado() {
		return codfidelizado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.CODFIDELIZADO
	 * @param codfidelizado  the value for x_local_fidelizados_tbl.CODFIDELIZADO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setCodfidelizado(String codfidelizado) {
		this.codfidelizado = codfidelizado == null ? null : codfidelizado
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.CODLENGUA
	 * @return  the value of x_local_fidelizados_tbl.CODLENGUA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getCodlengua() {
		return codlengua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.CODLENGUA
	 * @param codlengua  the value for x_local_fidelizados_tbl.CODLENGUA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setCodlengua(String codlengua) {
		this.codlengua = codlengua == null ? null : codlengua.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.TELEFONO
	 * @return  the value of x_local_fidelizados_tbl.TELEFONO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.TELEFONO
	 * @param telefono  the value for x_local_fidelizados_tbl.TELEFONO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono == null ? null : telefono.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.EMAIL
	 * @return  the value of x_local_fidelizados_tbl.EMAIL
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.EMAIL
	 * @param email  the value for x_local_fidelizados_tbl.EMAIL
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.NUMERO_TARJETA
	 * @return  the value of x_local_fidelizados_tbl.NUMERO_TARJETA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getNumeroTarjeta() {
		return numeroTarjeta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.NUMERO_TARJETA
	 * @param numeroTarjeta  the value for x_local_fidelizados_tbl.NUMERO_TARJETA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta == null ? null : numeroTarjeta
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.FECHA_VERSION
	 * @return  the value of x_local_fidelizados_tbl.FECHA_VERSION
	 * @mbggenerated  Thu Jan 16 17:04:58 CET 2025
	 */
	public Date getFechaVersion() {
		return fechaVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.FECHA_VERSION
	 * @param fechaVersion  the value for x_local_fidelizados_tbl.FECHA_VERSION
	 * @mbggenerated  Thu Jan 16 17:04:58 CET 2025
	 */
	public void setFechaVersion(Date fechaVersion) {
		this.fechaVersion = fechaVersion;
	}
}