package com.comerzzia.iskaypet.pos.persistence.fidelizacion.fidelizados;

public class LocalFidelizadosKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.UID_INSTANCIA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private String uidInstancia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column x_local_fidelizados_tbl.ID_FIDELIZADO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	private Long idFidelizado;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.UID_INSTANCIA
	 * @return  the value of x_local_fidelizados_tbl.UID_INSTANCIA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getUidInstancia() {
		return uidInstancia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.UID_INSTANCIA
	 * @param uidInstancia  the value for x_local_fidelizados_tbl.UID_INSTANCIA
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setUidInstancia(String uidInstancia) {
		this.uidInstancia = uidInstancia == null ? null : uidInstancia.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column x_local_fidelizados_tbl.ID_FIDELIZADO
	 * @return  the value of x_local_fidelizados_tbl.ID_FIDELIZADO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public Long getIdFidelizado() {
		return idFidelizado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column x_local_fidelizados_tbl.ID_FIDELIZADO
	 * @param idFidelizado  the value for x_local_fidelizados_tbl.ID_FIDELIZADO
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setIdFidelizado(Long idFidelizado) {
		this.idFidelizado = idFidelizado;
	}
}