package com.comerzzia.iskaypet.pos.persistence.fidelizacion.fidelizados;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LocalFidelizadosMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int countByExample(LocalFidelizadosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int deleteByExample(LocalFidelizadosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int deleteByPrimaryKey(LocalFidelizadosKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int insert(LocalFidelizados record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int insertSelective(LocalFidelizados record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	List<LocalFidelizados> selectByExampleWithRowbounds(
			LocalFidelizadosExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	List<LocalFidelizados> selectByExample(LocalFidelizadosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	LocalFidelizados selectByPrimaryKey(LocalFidelizadosKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int updateByExampleSelective(@Param("record") LocalFidelizados record,
			@Param("example") LocalFidelizadosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int updateByExample(@Param("record") LocalFidelizados record,
			@Param("example") LocalFidelizadosExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int updateByPrimaryKeySelective(LocalFidelizados record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	int updateByPrimaryKey(LocalFidelizados record);
}