package com.comerzzia.iskaypet.pos.persistence.fidelizacion.fidelizados;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LocalFidelizadosExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public LocalFidelizadosExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUidInstanciaIsNull() {
			addCriterion("UID_INSTANCIA is null");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaIsNotNull() {
			addCriterion("UID_INSTANCIA is not null");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaEqualTo(String value) {
			addCriterion("UID_INSTANCIA =", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaNotEqualTo(String value) {
			addCriterion("UID_INSTANCIA <>", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaGreaterThan(String value) {
			addCriterion("UID_INSTANCIA >", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaGreaterThanOrEqualTo(String value) {
			addCriterion("UID_INSTANCIA >=", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaLessThan(String value) {
			addCriterion("UID_INSTANCIA <", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaLessThanOrEqualTo(String value) {
			addCriterion("UID_INSTANCIA <=", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaLike(String value) {
			addCriterion("UID_INSTANCIA like", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaNotLike(String value) {
			addCriterion("UID_INSTANCIA not like", value, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaIn(List<String> values) {
			addCriterion("UID_INSTANCIA in", values, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaNotIn(List<String> values) {
			addCriterion("UID_INSTANCIA not in", values, "uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaBetween(String value1, String value2) {
			addCriterion("UID_INSTANCIA between", value1, value2,
					"uidInstancia");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaNotBetween(String value1, String value2) {
			addCriterion("UID_INSTANCIA not between", value1, value2,
					"uidInstancia");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoIsNull() {
			addCriterion("ID_FIDELIZADO is null");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoIsNotNull() {
			addCriterion("ID_FIDELIZADO is not null");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoEqualTo(Long value) {
			addCriterion("ID_FIDELIZADO =", value, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoNotEqualTo(Long value) {
			addCriterion("ID_FIDELIZADO <>", value, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoGreaterThan(Long value) {
			addCriterion("ID_FIDELIZADO >", value, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoGreaterThanOrEqualTo(Long value) {
			addCriterion("ID_FIDELIZADO >=", value, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoLessThan(Long value) {
			addCriterion("ID_FIDELIZADO <", value, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoLessThanOrEqualTo(Long value) {
			addCriterion("ID_FIDELIZADO <=", value, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoIn(List<Long> values) {
			addCriterion("ID_FIDELIZADO in", values, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoNotIn(List<Long> values) {
			addCriterion("ID_FIDELIZADO not in", values, "idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoBetween(Long value1, Long value2) {
			addCriterion("ID_FIDELIZADO between", value1, value2,
					"idFidelizado");
			return (Criteria) this;
		}

		public Criteria andIdFidelizadoNotBetween(Long value1, Long value2) {
			addCriterion("ID_FIDELIZADO not between", value1, value2,
					"idFidelizado");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("NOMBRE is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("NOMBRE is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("NOMBRE =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("NOMBRE <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("NOMBRE >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("NOMBRE <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("NOMBRE like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("NOMBRE not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("NOMBRE in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("NOMBRE not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("NOMBRE between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("NOMBRE not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andApellidosIsNull() {
			addCriterion("APELLIDOS is null");
			return (Criteria) this;
		}

		public Criteria andApellidosIsNotNull() {
			addCriterion("APELLIDOS is not null");
			return (Criteria) this;
		}

		public Criteria andApellidosEqualTo(String value) {
			addCriterion("APELLIDOS =", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosNotEqualTo(String value) {
			addCriterion("APELLIDOS <>", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosGreaterThan(String value) {
			addCriterion("APELLIDOS >", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosGreaterThanOrEqualTo(String value) {
			addCriterion("APELLIDOS >=", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosLessThan(String value) {
			addCriterion("APELLIDOS <", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosLessThanOrEqualTo(String value) {
			addCriterion("APELLIDOS <=", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosLike(String value) {
			addCriterion("APELLIDOS like", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosNotLike(String value) {
			addCriterion("APELLIDOS not like", value, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosIn(List<String> values) {
			addCriterion("APELLIDOS in", values, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosNotIn(List<String> values) {
			addCriterion("APELLIDOS not in", values, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosBetween(String value1, String value2) {
			addCriterion("APELLIDOS between", value1, value2, "apellidos");
			return (Criteria) this;
		}

		public Criteria andApellidosNotBetween(String value1, String value2) {
			addCriterion("APELLIDOS not between", value1, value2, "apellidos");
			return (Criteria) this;
		}

		public Criteria andDomicilioIsNull() {
			addCriterion("DOMICILIO is null");
			return (Criteria) this;
		}

		public Criteria andDomicilioIsNotNull() {
			addCriterion("DOMICILIO is not null");
			return (Criteria) this;
		}

		public Criteria andDomicilioEqualTo(String value) {
			addCriterion("DOMICILIO =", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotEqualTo(String value) {
			addCriterion("DOMICILIO <>", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioGreaterThan(String value) {
			addCriterion("DOMICILIO >", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioGreaterThanOrEqualTo(String value) {
			addCriterion("DOMICILIO >=", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLessThan(String value) {
			addCriterion("DOMICILIO <", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLessThanOrEqualTo(String value) {
			addCriterion("DOMICILIO <=", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioLike(String value) {
			addCriterion("DOMICILIO like", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotLike(String value) {
			addCriterion("DOMICILIO not like", value, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioIn(List<String> values) {
			addCriterion("DOMICILIO in", values, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotIn(List<String> values) {
			addCriterion("DOMICILIO not in", values, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioBetween(String value1, String value2) {
			addCriterion("DOMICILIO between", value1, value2, "domicilio");
			return (Criteria) this;
		}

		public Criteria andDomicilioNotBetween(String value1, String value2) {
			addCriterion("DOMICILIO not between", value1, value2, "domicilio");
			return (Criteria) this;
		}

		public Criteria andLocalidadIsNull() {
			addCriterion("LOCALIDAD is null");
			return (Criteria) this;
		}

		public Criteria andLocalidadIsNotNull() {
			addCriterion("LOCALIDAD is not null");
			return (Criteria) this;
		}

		public Criteria andLocalidadEqualTo(String value) {
			addCriterion("LOCALIDAD =", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadNotEqualTo(String value) {
			addCriterion("LOCALIDAD <>", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadGreaterThan(String value) {
			addCriterion("LOCALIDAD >", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadGreaterThanOrEqualTo(String value) {
			addCriterion("LOCALIDAD >=", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadLessThan(String value) {
			addCriterion("LOCALIDAD <", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadLessThanOrEqualTo(String value) {
			addCriterion("LOCALIDAD <=", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadLike(String value) {
			addCriterion("LOCALIDAD like", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadNotLike(String value) {
			addCriterion("LOCALIDAD not like", value, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadIn(List<String> values) {
			addCriterion("LOCALIDAD in", values, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadNotIn(List<String> values) {
			addCriterion("LOCALIDAD not in", values, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadBetween(String value1, String value2) {
			addCriterion("LOCALIDAD between", value1, value2, "localidad");
			return (Criteria) this;
		}

		public Criteria andLocalidadNotBetween(String value1, String value2) {
			addCriterion("LOCALIDAD not between", value1, value2, "localidad");
			return (Criteria) this;
		}

		public Criteria andProvinciaIsNull() {
			addCriterion("PROVINCIA is null");
			return (Criteria) this;
		}

		public Criteria andProvinciaIsNotNull() {
			addCriterion("PROVINCIA is not null");
			return (Criteria) this;
		}

		public Criteria andProvinciaEqualTo(String value) {
			addCriterion("PROVINCIA =", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaNotEqualTo(String value) {
			addCriterion("PROVINCIA <>", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaGreaterThan(String value) {
			addCriterion("PROVINCIA >", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaGreaterThanOrEqualTo(String value) {
			addCriterion("PROVINCIA >=", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaLessThan(String value) {
			addCriterion("PROVINCIA <", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaLessThanOrEqualTo(String value) {
			addCriterion("PROVINCIA <=", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaLike(String value) {
			addCriterion("PROVINCIA like", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaNotLike(String value) {
			addCriterion("PROVINCIA not like", value, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaIn(List<String> values) {
			addCriterion("PROVINCIA in", values, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaNotIn(List<String> values) {
			addCriterion("PROVINCIA not in", values, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaBetween(String value1, String value2) {
			addCriterion("PROVINCIA between", value1, value2, "provincia");
			return (Criteria) this;
		}

		public Criteria andProvinciaNotBetween(String value1, String value2) {
			addCriterion("PROVINCIA not between", value1, value2, "provincia");
			return (Criteria) this;
		}

		public Criteria andCpIsNull() {
			addCriterion("CP is null");
			return (Criteria) this;
		}

		public Criteria andCpIsNotNull() {
			addCriterion("CP is not null");
			return (Criteria) this;
		}

		public Criteria andCpEqualTo(String value) {
			addCriterion("CP =", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpNotEqualTo(String value) {
			addCriterion("CP <>", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpGreaterThan(String value) {
			addCriterion("CP >", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpGreaterThanOrEqualTo(String value) {
			addCriterion("CP >=", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpLessThan(String value) {
			addCriterion("CP <", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpLessThanOrEqualTo(String value) {
			addCriterion("CP <=", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpLike(String value) {
			addCriterion("CP like", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpNotLike(String value) {
			addCriterion("CP not like", value, "cp");
			return (Criteria) this;
		}

		public Criteria andCpIn(List<String> values) {
			addCriterion("CP in", values, "cp");
			return (Criteria) this;
		}

		public Criteria andCpNotIn(List<String> values) {
			addCriterion("CP not in", values, "cp");
			return (Criteria) this;
		}

		public Criteria andCpBetween(String value1, String value2) {
			addCriterion("CP between", value1, value2, "cp");
			return (Criteria) this;
		}

		public Criteria andCpNotBetween(String value1, String value2) {
			addCriterion("CP not between", value1, value2, "cp");
			return (Criteria) this;
		}

		public Criteria andCodpaisIsNull() {
			addCriterion("CODPAIS is null");
			return (Criteria) this;
		}

		public Criteria andCodpaisIsNotNull() {
			addCriterion("CODPAIS is not null");
			return (Criteria) this;
		}

		public Criteria andCodpaisEqualTo(String value) {
			addCriterion("CODPAIS =", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisNotEqualTo(String value) {
			addCriterion("CODPAIS <>", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisGreaterThan(String value) {
			addCriterion("CODPAIS >", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisGreaterThanOrEqualTo(String value) {
			addCriterion("CODPAIS >=", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisLessThan(String value) {
			addCriterion("CODPAIS <", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisLessThanOrEqualTo(String value) {
			addCriterion("CODPAIS <=", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisLike(String value) {
			addCriterion("CODPAIS like", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisNotLike(String value) {
			addCriterion("CODPAIS not like", value, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisIn(List<String> values) {
			addCriterion("CODPAIS in", values, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisNotIn(List<String> values) {
			addCriterion("CODPAIS not in", values, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisBetween(String value1, String value2) {
			addCriterion("CODPAIS between", value1, value2, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodpaisNotBetween(String value1, String value2) {
			addCriterion("CODPAIS not between", value1, value2, "codpais");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenIsNull() {
			addCriterion("CODTIPOIDEN is null");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenIsNotNull() {
			addCriterion("CODTIPOIDEN is not null");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenEqualTo(String value) {
			addCriterion("CODTIPOIDEN =", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenNotEqualTo(String value) {
			addCriterion("CODTIPOIDEN <>", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenGreaterThan(String value) {
			addCriterion("CODTIPOIDEN >", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenGreaterThanOrEqualTo(String value) {
			addCriterion("CODTIPOIDEN >=", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenLessThan(String value) {
			addCriterion("CODTIPOIDEN <", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenLessThanOrEqualTo(String value) {
			addCriterion("CODTIPOIDEN <=", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenLike(String value) {
			addCriterion("CODTIPOIDEN like", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenNotLike(String value) {
			addCriterion("CODTIPOIDEN not like", value, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenIn(List<String> values) {
			addCriterion("CODTIPOIDEN in", values, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenNotIn(List<String> values) {
			addCriterion("CODTIPOIDEN not in", values, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenBetween(String value1, String value2) {
			addCriterion("CODTIPOIDEN between", value1, value2, "codtipoiden");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenNotBetween(String value1, String value2) {
			addCriterion("CODTIPOIDEN not between", value1, value2,
					"codtipoiden");
			return (Criteria) this;
		}

		public Criteria andDocumentoIsNull() {
			addCriterion("DOCUMENTO is null");
			return (Criteria) this;
		}

		public Criteria andDocumentoIsNotNull() {
			addCriterion("DOCUMENTO is not null");
			return (Criteria) this;
		}

		public Criteria andDocumentoEqualTo(String value) {
			addCriterion("DOCUMENTO =", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoNotEqualTo(String value) {
			addCriterion("DOCUMENTO <>", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoGreaterThan(String value) {
			addCriterion("DOCUMENTO >", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoGreaterThanOrEqualTo(String value) {
			addCriterion("DOCUMENTO >=", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoLessThan(String value) {
			addCriterion("DOCUMENTO <", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoLessThanOrEqualTo(String value) {
			addCriterion("DOCUMENTO <=", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoLike(String value) {
			addCriterion("DOCUMENTO like", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoNotLike(String value) {
			addCriterion("DOCUMENTO not like", value, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoIn(List<String> values) {
			addCriterion("DOCUMENTO in", values, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoNotIn(List<String> values) {
			addCriterion("DOCUMENTO not in", values, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoBetween(String value1, String value2) {
			addCriterion("DOCUMENTO between", value1, value2, "documento");
			return (Criteria) this;
		}

		public Criteria andDocumentoNotBetween(String value1, String value2) {
			addCriterion("DOCUMENTO not between", value1, value2, "documento");
			return (Criteria) this;
		}

		public Criteria andFechaAltaIsNull() {
			addCriterion("FECHA_ALTA is null");
			return (Criteria) this;
		}

		public Criteria andFechaAltaIsNotNull() {
			addCriterion("FECHA_ALTA is not null");
			return (Criteria) this;
		}

		public Criteria andFechaAltaEqualTo(Date value) {
			addCriterion("FECHA_ALTA =", value, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaNotEqualTo(Date value) {
			addCriterion("FECHA_ALTA <>", value, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaGreaterThan(Date value) {
			addCriterion("FECHA_ALTA >", value, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaGreaterThanOrEqualTo(Date value) {
			addCriterion("FECHA_ALTA >=", value, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaLessThan(Date value) {
			addCriterion("FECHA_ALTA <", value, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaLessThanOrEqualTo(Date value) {
			addCriterion("FECHA_ALTA <=", value, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaIn(List<Date> values) {
			addCriterion("FECHA_ALTA in", values, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaNotIn(List<Date> values) {
			addCriterion("FECHA_ALTA not in", values, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaBetween(Date value1, Date value2) {
			addCriterion("FECHA_ALTA between", value1, value2, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaAltaNotBetween(Date value1, Date value2) {
			addCriterion("FECHA_ALTA not between", value1, value2, "fechaAlta");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionIsNull() {
			addCriterion("FECHA_MODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionIsNotNull() {
			addCriterion("FECHA_MODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionEqualTo(Date value) {
			addCriterion("FECHA_MODIFICACION =", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionNotEqualTo(Date value) {
			addCriterion("FECHA_MODIFICACION <>", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionGreaterThan(Date value) {
			addCriterion("FECHA_MODIFICACION >", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionGreaterThanOrEqualTo(Date value) {
			addCriterion("FECHA_MODIFICACION >=", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionLessThan(Date value) {
			addCriterion("FECHA_MODIFICACION <", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionLessThanOrEqualTo(Date value) {
			addCriterion("FECHA_MODIFICACION <=", value, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionIn(List<Date> values) {
			addCriterion("FECHA_MODIFICACION in", values, "fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionNotIn(List<Date> values) {
			addCriterion("FECHA_MODIFICACION not in", values,
					"fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionBetween(Date value1, Date value2) {
			addCriterion("FECHA_MODIFICACION between", value1, value2,
					"fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaModificacionNotBetween(Date value1, Date value2) {
			addCriterion("FECHA_MODIFICACION not between", value1, value2,
					"fechaModificacion");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoIsNull() {
			addCriterion("CODFIDELIZADO is null");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoIsNotNull() {
			addCriterion("CODFIDELIZADO is not null");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoEqualTo(String value) {
			addCriterion("CODFIDELIZADO =", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoNotEqualTo(String value) {
			addCriterion("CODFIDELIZADO <>", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoGreaterThan(String value) {
			addCriterion("CODFIDELIZADO >", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoGreaterThanOrEqualTo(String value) {
			addCriterion("CODFIDELIZADO >=", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoLessThan(String value) {
			addCriterion("CODFIDELIZADO <", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoLessThanOrEqualTo(String value) {
			addCriterion("CODFIDELIZADO <=", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoLike(String value) {
			addCriterion("CODFIDELIZADO like", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoNotLike(String value) {
			addCriterion("CODFIDELIZADO not like", value, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoIn(List<String> values) {
			addCriterion("CODFIDELIZADO in", values, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoNotIn(List<String> values) {
			addCriterion("CODFIDELIZADO not in", values, "codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoBetween(String value1, String value2) {
			addCriterion("CODFIDELIZADO between", value1, value2,
					"codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoNotBetween(String value1, String value2) {
			addCriterion("CODFIDELIZADO not between", value1, value2,
					"codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodlenguaIsNull() {
			addCriterion("CODLENGUA is null");
			return (Criteria) this;
		}

		public Criteria andCodlenguaIsNotNull() {
			addCriterion("CODLENGUA is not null");
			return (Criteria) this;
		}

		public Criteria andCodlenguaEqualTo(String value) {
			addCriterion("CODLENGUA =", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaNotEqualTo(String value) {
			addCriterion("CODLENGUA <>", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaGreaterThan(String value) {
			addCriterion("CODLENGUA >", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaGreaterThanOrEqualTo(String value) {
			addCriterion("CODLENGUA >=", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaLessThan(String value) {
			addCriterion("CODLENGUA <", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaLessThanOrEqualTo(String value) {
			addCriterion("CODLENGUA <=", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaLike(String value) {
			addCriterion("CODLENGUA like", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaNotLike(String value) {
			addCriterion("CODLENGUA not like", value, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaIn(List<String> values) {
			addCriterion("CODLENGUA in", values, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaNotIn(List<String> values) {
			addCriterion("CODLENGUA not in", values, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaBetween(String value1, String value2) {
			addCriterion("CODLENGUA between", value1, value2, "codlengua");
			return (Criteria) this;
		}

		public Criteria andCodlenguaNotBetween(String value1, String value2) {
			addCriterion("CODLENGUA not between", value1, value2, "codlengua");
			return (Criteria) this;
		}

		public Criteria andTelefonoIsNull() {
			addCriterion("TELEFONO is null");
			return (Criteria) this;
		}

		public Criteria andTelefonoIsNotNull() {
			addCriterion("TELEFONO is not null");
			return (Criteria) this;
		}

		public Criteria andTelefonoEqualTo(String value) {
			addCriterion("TELEFONO =", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotEqualTo(String value) {
			addCriterion("TELEFONO <>", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoGreaterThan(String value) {
			addCriterion("TELEFONO >", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
			addCriterion("TELEFONO >=", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLessThan(String value) {
			addCriterion("TELEFONO <", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLessThanOrEqualTo(String value) {
			addCriterion("TELEFONO <=", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLike(String value) {
			addCriterion("TELEFONO like", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotLike(String value) {
			addCriterion("TELEFONO not like", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoIn(List<String> values) {
			addCriterion("TELEFONO in", values, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotIn(List<String> values) {
			addCriterion("TELEFONO not in", values, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoBetween(String value1, String value2) {
			addCriterion("TELEFONO between", value1, value2, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotBetween(String value1, String value2) {
			addCriterion("TELEFONO not between", value1, value2, "telefono");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaIsNull() {
			addCriterion("NUMERO_TARJETA is null");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaIsNotNull() {
			addCriterion("NUMERO_TARJETA is not null");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaEqualTo(String value) {
			addCriterion("NUMERO_TARJETA =", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaNotEqualTo(String value) {
			addCriterion("NUMERO_TARJETA <>", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaGreaterThan(String value) {
			addCriterion("NUMERO_TARJETA >", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaGreaterThanOrEqualTo(String value) {
			addCriterion("NUMERO_TARJETA >=", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaLessThan(String value) {
			addCriterion("NUMERO_TARJETA <", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaLessThanOrEqualTo(String value) {
			addCriterion("NUMERO_TARJETA <=", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaLike(String value) {
			addCriterion("NUMERO_TARJETA like", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaNotLike(String value) {
			addCriterion("NUMERO_TARJETA not like", value, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaIn(List<String> values) {
			addCriterion("NUMERO_TARJETA in", values, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaNotIn(List<String> values) {
			addCriterion("NUMERO_TARJETA not in", values, "numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaBetween(String value1, String value2) {
			addCriterion("NUMERO_TARJETA between", value1, value2,
					"numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaNotBetween(String value1, String value2) {
			addCriterion("NUMERO_TARJETA not between", value1, value2,
					"numeroTarjeta");
			return (Criteria) this;
		}

		public Criteria andFechaVersionIsNull() {
			addCriterion("FECHA_VERSION is null");
			return (Criteria) this;
		}

		public Criteria andFechaVersionIsNotNull() {
			addCriterion("FECHA_VERSION is not null");
			return (Criteria) this;
		}

		public Criteria andFechaVersionEqualTo(Date value) {
			addCriterion("FECHA_VERSION =", value, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionNotEqualTo(Date value) {
			addCriterion("FECHA_VERSION <>", value, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionGreaterThan(Date value) {
			addCriterion("FECHA_VERSION >", value, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionGreaterThanOrEqualTo(Date value) {
			addCriterion("FECHA_VERSION >=", value, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionLessThan(Date value) {
			addCriterion("FECHA_VERSION <", value, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionLessThanOrEqualTo(Date value) {
			addCriterion("FECHA_VERSION <=", value, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionIn(List<Date> values) {
			addCriterion("FECHA_VERSION in", values, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionNotIn(List<Date> values) {
			addCriterion("FECHA_VERSION not in", values, "fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionBetween(Date value1, Date value2) {
			addCriterion("FECHA_VERSION between", value1, value2,
					"fechaVersion");
			return (Criteria) this;
		}

		public Criteria andFechaVersionNotBetween(Date value1, Date value2) {
			addCriterion("FECHA_VERSION not between", value1, value2,
					"fechaVersion");
			return (Criteria) this;
		}

		public Criteria andUidInstanciaLikeInsensitive(String value) {
			addCriterion("upper(UID_INSTANCIA) like", value.toUpperCase(),
					"uidInstancia");
			return (Criteria) this;
		}

		public Criteria andNombreLikeInsensitive(String value) {
			addCriterion("upper(NOMBRE) like", value.toUpperCase(), "nombre");
			return (Criteria) this;
		}

		public Criteria andApellidosLikeInsensitive(String value) {
			addCriterion("upper(APELLIDOS) like", value.toUpperCase(),
					"apellidos");
			return (Criteria) this;
		}

		public Criteria andDomicilioLikeInsensitive(String value) {
			addCriterion("upper(DOMICILIO) like", value.toUpperCase(),
					"domicilio");
			return (Criteria) this;
		}

		public Criteria andLocalidadLikeInsensitive(String value) {
			addCriterion("upper(LOCALIDAD) like", value.toUpperCase(),
					"localidad");
			return (Criteria) this;
		}

		public Criteria andProvinciaLikeInsensitive(String value) {
			addCriterion("upper(PROVINCIA) like", value.toUpperCase(),
					"provincia");
			return (Criteria) this;
		}

		public Criteria andCpLikeInsensitive(String value) {
			addCriterion("upper(CP) like", value.toUpperCase(), "cp");
			return (Criteria) this;
		}

		public Criteria andCodpaisLikeInsensitive(String value) {
			addCriterion("upper(CODPAIS) like", value.toUpperCase(), "codpais");
			return (Criteria) this;
		}

		public Criteria andCodtipoidenLikeInsensitive(String value) {
			addCriterion("upper(CODTIPOIDEN) like", value.toUpperCase(),
					"codtipoiden");
			return (Criteria) this;
		}

		public Criteria andDocumentoLikeInsensitive(String value) {
			addCriterion("upper(DOCUMENTO) like", value.toUpperCase(),
					"documento");
			return (Criteria) this;
		}

		public Criteria andCodfidelizadoLikeInsensitive(String value) {
			addCriterion("upper(CODFIDELIZADO) like", value.toUpperCase(),
					"codfidelizado");
			return (Criteria) this;
		}

		public Criteria andCodlenguaLikeInsensitive(String value) {
			addCriterion("upper(CODLENGUA) like", value.toUpperCase(),
					"codlengua");
			return (Criteria) this;
		}

		public Criteria andTelefonoLikeInsensitive(String value) {
			addCriterion("upper(TELEFONO) like", value.toUpperCase(),
					"telefono");
			return (Criteria) this;
		}

		public Criteria andEmailLikeInsensitive(String value) {
			addCriterion("upper(EMAIL) like", value.toUpperCase(), "email");
			return (Criteria) this;
		}

		public Criteria andNumeroTarjetaLikeInsensitive(String value) {
			addCriterion("upper(NUMERO_TARJETA) like", value.toUpperCase(),
					"numeroTarjeta");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table x_local_fidelizados_tbl
	 * @mbggenerated  Wed Jan 15 22:55:58 CET 2025
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table x_local_fidelizados_tbl
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 15 22:55:58 CET 2025
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}