package com.comerzzia.bimbaylola.pos.services.spark130f;

import java.util.HashMap;
import java.util.Map;

import com.comerzzia.pos.util.i18n.I18N;

public class Spark130FConstants {

	public static final String NO_ERROR = "0";
	public static final String DM_INCORRECTO = "2000";

	public static final String TAG_KASSA = "Kassa";
	public static final String TAG_DATEFD = "DateFD";
	public static final String TAG_TIMEFD = "TimeFD";
	public static final String TAG_SUMCK = "SumCk";
	
	public static final String ATT_FD = "FD";
	public static final String ATT_FP = "FP";
	public static final String ATT_CHECK = "CHECK";
	public static final String ATT_RC = "RC";
	
	public static final String NODE_VALUE = "nodeValue";
	
	public static Map<String, String> setErrors() {
		Map<String, String> map_error = new HashMap<String, String>();
		// map_error.put("0", I18N.getTexto("no error"));
		map_error.put("1", I18N.getTexto("unknown operation"));
		map_error.put("2", I18N.getTexto("not enough memory to complete the operation"));
		map_error.put("3", I18N.getTexto("operation not specified"));
		map_error.put("4", I18N.getTexto("the structure of storage of the error of the FN operation is not specified"));
		map_error.put("5", I18N.getTexto("the structure of the results of the FN operation is not specified"));
		map_error.put("6", I18N.getTexto("the structure of the input parameters of the FN operation is not specified"));
		map_error.put("7", I18N.getTexto("exceeded the maximum data size for the FN command"));
		map_error.put("8", I18N.getTexto("error in classifier"));
		map_error.put("10", I18N.getTexto("error of the initial state of the FN before (re-) registration"));
		map_error.put("11", I18N.getTexto("FN error when receiving status"));
		map_error.put("12", I18N.getTexto("FN error when issuing the command \"Start registration report\""));
		map_error.put("13", I18N.getTexto("FN error when issuing the command \"Transfer document data\""));
		map_error.put("14", I18N.getTexto("FN error when issuing the command \"Generate a report on registration (re-registration) of FCR\""));
		map_error.put("15", I18N.getTexto("FN error when issuing the command \"Start closing the FN fiscal mode\""));
		map_error.put("16", I18N.getTexto("FN error when issuing the command \"Close FN fiscal mode\""));
		map_error.put("17", I18N.getTexto("error when trying to capture FN"));
		map_error.put("18", I18N.getTexto("FN error when issuing the command \"Start generating a report on the current state of calculations\""));
		map_error.put("19", I18N.getTexto("FN error when issuing the command \"Generate a report on the current state of calculations\""));
		map_error.put("20", I18N.getTexto("FN error: shift is open"));
		map_error.put("21", I18N.getTexto("FN error: shift is closed"));
		map_error.put("22", I18N.getTexto("FN error: there is an unclosed document"));
		map_error.put("23", I18N.getTexto("FN error when issuing the command \"Request for the number of FDs for which there is no receipt\""));
		map_error.put("24", I18N.getTexto("FN error when issuing the command \"Request for FN validity period\""));
		map_error.put("25", I18N.getTexto("FN error when issuing the command \"Request for FN fiscalization results\""));
		map_error.put("26", I18N.getTexto("FN error: there are documents unconfirmed in the FDO"));
		map_error.put("27", I18N.getTexto("FN error when issuing the command \"Start opening shift\""));
		map_error.put("28", I18N.getTexto("FN error when issuing the command \"Open shift\""));
		map_error.put("29", I18N.getTexto("FN error when issuing the command \"Start closing shift\""));
		map_error.put("30", I18N.getTexto("FN error when issuing the command \"Close shift\""));
		map_error.put("31", I18N.getTexto("FN error when issuing the command \"Start receipt formation (SRF)\""));
		map_error.put("32", I18N.getTexto("type definition error: check or SRF"));
		map_error.put("33", I18N.getTexto("FN error: check is not open"));
		map_error.put("34", I18N.getTexto("data conversion error"));
		map_error.put("35", I18N.getTexto("FN error when issuing the \"Generate check\" command"));
		map_error.put("36", I18N.getTexto("FN error when issuing the command \"Undo the current document\""));
		map_error.put("37", I18N.getTexto("error: unclosed document is missing"));
		map_error.put("38", I18N.getTexto("error: shift overdue"));
		map_error.put("39", I18N.getTexto("error: correction check is not open"));
		map_error.put("40", I18N.getTexto("FN error when receiving counters"));
		map_error.put("41", I18N.getTexto("FN error when receiving the shift state"));
		map_error.put("42", I18N.getTexto("error: the check is empty (no items for calculation)"));
		map_error.put("43", I18N.getTexto("error: the stage of the receipt formation does not correspond to the operation"));
		map_error.put("44", I18N.getTexto("FN error when issuing the command \"Request for the number and type of FN software version\""));
		map_error.put("45", I18N.getTexto("error: a debug version of the FN is needed to perform the operation"));
		map_error.put("46", I18N.getTexto("FN error when issuing the \"FN Reset\" command"));
		map_error.put("47", I18N.getTexto("FN error when receiving the status of information exchange with the FDO"));
		map_error.put("48", I18N.getTexto("FN error: message reading for FDO has already started"));
		map_error.put("49", I18N.getTexto("FN error: no messages for FDO"));
		map_error.put("50", I18N.getTexto("FN error when issuing the command \"Send the status of the transport connection with the FDO server\""));
		map_error.put("51", I18N.getTexto("FN error when issuing the command \"Start reading a message for the FDO server\""));
		map_error.put("52", I18N.getTexto("FN error: message reading for FDO has not started yet"));
		map_error.put("53", I18N.getTexto("FN error when issuing the command \"Cancel message reading for the FDO server\""));
		map_error.put("54", I18N.getTexto("FN error when issuing the command \"Read message block for the FDO server\""));
		map_error.put("55", I18N.getTexto("FN error: there is no readiness to accept a receipt from the FDO"));
		map_error.put("56", I18N.getTexto("FN error when issuing the command \"Send a receipt from the FDO server\""));
		map_error.put("57", I18N.getTexto("FN error: incorrect fiscal signature"));
		map_error.put("58", I18N.getTexto("FN error: invalid receipt format"));
		map_error.put("59", I18N.getTexto("FN error: invalid FD number"));
		map_error.put("60", I18N.getTexto("FN error: wrong FN number"));
		map_error.put("61", I18N.getTexto("FN error: invalid CRC"));
		map_error.put("62", I18N.getTexto("FN error when issuing the command \"Request for a fiscal document in TLV format\""));
		map_error.put("63", I18N.getTexto("FN error when issuing the command \"Reading the TLV of the fiscal document\""));
		map_error.put("64", I18N.getTexto("FN error: the compulsory document data is missing in the archive"));
		map_error.put("65", I18N.getTexto("FN error: the document requested from the archive is not a receipt"));
		map_error.put("66", I18N.getTexto("FN error when issuing the command \"Request for the total size of data transmitted by command 07h\""));
		map_error.put("67", I18N.getTexto("FN error when issuing the command \"Request for FN format\""));
		map_error.put("68", I18N.getTexto("FN error: erroneous data received from FN"));
		map_error.put("94", I18N.getTexto("Timeout for receiving a command"));
		map_error.put("95", I18N.getTexto("Print device is busy ..."));
		map_error.put("96", I18N.getTexto("Unknown parameters specified in the command"));
		map_error.put("97", I18N.getTexto("The command is missing compulsory parameters"));
		map_error.put("98", I18N.getTexto("The command contains parameters, but they should not be"));
		map_error.put("99", I18N.getTexto("Invalid command format or unknown command"));
		map_error.put("100", I18N.getTexto("error in specifying the version of the FFD FCR"));
		map_error.put("101", I18N.getTexto("error in setting the serial number of the FCR"));
		map_error.put("102", I18N.getTexto("error in specifying the FCR version"));
		map_error.put("103", I18N.getTexto("error in setting the registration number of the FCR"));
		map_error.put("104", I18N.getTexto("error in setting TIN"));
		map_error.put("105", I18N.getTexto("error in setting FDO TIN"));
		map_error.put("106", I18N.getTexto("error in specifying the reason for re-registration"));
		map_error.put("107", I18N.getTexto("error: the specified taxation system is not supported"));
		map_error.put("108", I18N.getTexto("error in specifying a calculation attribute"));
		map_error.put("109", I18N.getTexto("error in specifying the attribute of the payment method"));
		map_error.put("110", I18N.getTexto("error in specifying the attribute of the item"));
		map_error.put("111", I18N.getTexto("error in specifying the name of the item"));
		map_error.put("112", I18N.getTexto("error in setting the unit of measurement"));
		map_error.put("113", I18N.getTexto("error in setting the item code "));
		map_error.put("114", I18N.getTexto("error in specifying the quantity"));
		map_error.put("115", I18N.getTexto("error in setting the unit price of an item"));
		map_error.put("116", I18N.getTexto("error in setting the price value of the item"));
		map_error.put("117", I18N.getTexto("error in setting the VAT rate "));
		map_error.put("118", I18N.getTexto("error in calculating the amount of VAT per unit "));
		map_error.put("119", I18N.getTexto("error in calculating the amount of VAT "));
		map_error.put("120", I18N.getTexto("error: the calculation of the value of items exceeded the maximum allowable value"));
		map_error.put("121", I18N.getTexto("error: the calculation of the value for the check exceeded the amount of payments"));
		map_error.put("122", I18N.getTexto("an error in specifying the amount of accepted cash as payment for a check"));
		map_error.put("123", I18N.getTexto("error: the calculation of the cost by type of payment for the check exceeded the limit"));
		map_error.put("124", I18N.getTexto("error of obtaining the current time from the internal clock of the FCR"));
		map_error.put("125", I18N.getTexto("error: there can be only one item in a check with credit payment "));
		map_error.put("126", I18N.getTexto("error: cashier not set"));
		map_error.put("127", I18N.getTexto("error in setting the agent attribute"));
		map_error.put("128", I18N.getTexto("error: the document in electronic form is not generated"));
		map_error.put("129", I18N.getTexto("error: the maximum number of items with an item code has been exceeded"));
		map_error.put("130", I18N.getTexto("error: Attempt to re-set a unique parameter"));
		map_error.put("131", I18N.getTexto("error: vendor tax ID not specified"));
		map_error.put("132", I18N.getTexto("error: an attempt was made to set the quantity of a unique item"));
		map_error.put("133", I18N.getTexto("error: printer failure"));
		map_error.put("134", I18N.getTexto("failure to write to flash memory"));
		map_error.put("135", I18N.getTexto("update file was not loaded"));
		map_error.put("136", I18N.getTexto("the current version of FFD FN does not support the operation"));
		map_error.put("137", I18N.getTexto("current version of FFD FN is not supported"));
		map_error.put("138", I18N.getTexto("erroneous sequence of commands"));
		map_error.put("139", I18N.getTexto("work with excisable goods is prohibited"));
		map_error.put("140", I18N.getTexto("items with marked goods in receipts are prohibited"));		
		map_error.put("200", I18N.getTexto("error in setting the parameter of the FN operation"));
		map_error.put("201", I18N.getTexto("FN operation parameter not specified"));
		map_error.put("202", I18N.getTexto("error in setting the operating modes of the FCR"));
		map_error.put("203", I18N.getTexto("error in specifying extended operating modes of the FCR"));
		map_error.put("204", I18N.getTexto("error setting parameter with date / time"));
		map_error.put("205", I18N.getTexto("error in setting a parameter with a tax number"));
		map_error.put("206", I18N.getTexto("error in setting a parameter with a bit mask"));
		map_error.put("207", I18N.getTexto("error: line length too long"));
		map_error.put("208", I18N.getTexto("error: invalid data"));
		map_error.put("401", I18N.getTexto("error: unknown FN command"));
		map_error.put("402", I18N.getTexto("error: incorrect state of FN"));
		map_error.put("403", I18N.getTexto("error: FN failure"));
		map_error.put("404", I18N.getTexto("error: failure of the CRC"));
		map_error.put("405", I18N.getTexto("error: command parameters do not correspond to FN life stage"));
		map_error.put("407", I18N.getTexto("error: incorrect date and / or time"));
		map_error.put("408", I18N.getTexto("error: no requested data"));
		map_error.put("409", I18N.getTexto("error: incorrect value of command parameters"));
		map_error.put("410", I18N.getTexto("error: invalid command."));
		map_error.put("411", I18N.getTexto("error: invalid requisites."));
		map_error.put("412", I18N.getTexto("error: data duplication"));
		map_error.put("413", I18N.getTexto("error: there is no data compulsory for correct accounting in the FN"));
		map_error.put("414", I18N.getTexto("error: the number of items in the document has exceeded the allowed limit"));
		map_error.put("416", I18N.getTexto("error: oversized TLV data "));
		map_error.put("417", I18N.getTexto("error: no transport connection"));
		map_error.put("418", I18N.getTexto("error: FN resource limit over"));
		map_error.put("420", I18N.getTexto("error: FN resource limitation"));
		map_error.put("422", I18N.getTexto("error: shift duration exceeded"));
		map_error.put("423", I18N.getTexto("error: incorrect data on the time interval between fiscal documents"));
		map_error.put("424", I18N.getTexto("error: incorrect variable transferred by the cash register to the FN"));
		map_error.put("425", I18N.getTexto("error: incorrect variable with a sign of selling excisable goods"));
		map_error.put("432", I18N.getTexto("error: FDO message could not be received"));
		map_error.put("435", I18N.getTexto("DM verification key update service error"));
		map_error.put("436", I18N.getTexto("error: unknown response from the verification code verification key update service"));
		map_error.put("448", I18N.getTexto("error: it is required to repeat the procedure for updating DM verification keys"));
		map_error.put("450", I18N.getTexto("error: work with marked goods is prohibited"));
		map_error.put("451", I18N.getTexto("the correct sequence of sending commands for processing labeled goods is violated"));
		map_error.put("452", I18N.getTexto("error: work with marked goods is temporarily blocked"));
		map_error.put("453", I18N.getTexto("error: marking code check table is full"));
		map_error.put("454", I18N.getTexto("error: period exceeded 90 days since last update of verification keys"));
		map_error.put("460", I18N.getTexto("error: required requisites are missing in the TLV block"));
		map_error.put("462", I18N.getTexto("error: attribute 2007 contains a DM that was not previously checked in FN"));
		map_error.put("604", I18N.getTexto("error: Failed to contact the OISM server"));
		map_error.put("605", I18N.getTexto("error: empty response received from OISM"));
		map_error.put("606", I18N.getTexto("error: unable to contact OKP server"));
		map_error.put("607", I18N.getTexto("error: empty response received from OKP"));
		
		return map_error;
	}
}
